---
name: Jira to Slack
description: Create a Slack message when a Jira issue is created
version: 1
category: Notifications
author: Tolstoy Team
tags: [jira, slack, notification, integration]
inputs:
  - name: slack_channel
    type: string
    required: true
    description: Slack channel to post notifications
  - name: jira_project
    type: string
    required: true
    description: Jira project key to monitor
---
trigger:
  type: webhook
  source: jira
  event: issue.created

steps:
  - key: extract_issue_details
    action: extract
    inputs:
      source: "{{trigger.payload}}"
      fields:
        - issueKey: "{{issue.key}}"
        - summary: "{{issue.fields.summary}}"
        - assignee: "{{issue.fields.assignee.displayName}}"
        - priority: "{{issue.fields.priority.name}}"
        - project: "{{issue.fields.project.key}}"
    condition:
      field: "{{issue.fields.project.key}}"
      operator: "equals"
      value: "{{inputs.jira_project}}"

  - key: format_slack_message
    action: template
    inputs:
      template: |
        🎯 New Jira Issue Created
        
        *Issue:* <{{issue.self}}|{{extract_issue_details.outputs.issueKey}}>
        *Summary:* {{extract_issue_details.outputs.summary}}
        *Assignee:* {{extract_issue_details.outputs.assignee || "Unassigned"}}
        *Priority:* {{extract_issue_details.outputs.priority}}
        *Project:* {{extract_issue_details.outputs.project}}
        
        _Created via Tolstoy automation_ ⚡

  - key: send_slack_notification
    action: slack.post_message
    inputs:
      channel: "{{inputs.slack_channel}}"
      text: "{{format_slack_message.outputs.result}}"
      username: "Jira Bot"
      icon_emoji: ":jira:"