name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Quality Checks & Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npx eslint "src/**/*.ts"
      - run: npx tsc --noEmit  
      - run: npx prettier --check "src/**/*.ts"
      - run: npm run build
      - run: echo "✅ All quality checks passed!"

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 -d > ssh_key.pem
          chmod 600 ssh_key.pem

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" << 'EOF'
            set -e
            cd /home/ubuntu/tolstoy
            
            echo "🔍 Checking AWS configuration..."
            aws sts get-caller-identity || {
              echo "❌ AWS credentials not configured on this server"
              echo "Please ensure EC2 instance has IAM role or AWS credentials configured"
              exit 1
            }
            
            echo "📥 Pulling latest code..."
            # Handle any uncommitted changes by stashing them
            git stash || echo "No changes to stash"
            # Clean any untracked files that might conflict (like generated docs/openapi.json)
            git clean -fd docs/ || echo "No untracked files to clean"
            git pull origin main
            # Restore stashed changes if any (this will handle conflicts gracefully)
            git stash pop || echo "No stash to pop or merge conflicts - continuing"
            
            echo "📦 Installing dependencies..."
            npm ci --production=false
            
            echo "⚙️ Generating Prisma client..."
            npm run db:generate || echo "Prisma generate skipped"
            
            echo "🔨 Building application..."
            npm run build
            
            echo "🗃️ Running database migrations..."
            # Use GitHub secrets for database URLs during deployment
            export DATABASE_URL="${{ secrets.DATABASE_URL }}"
            export DIRECT_URL="${{ secrets.DIRECT_URL }}"
            echo "✅ Database URLs configured from GitHub secrets"
            
            timeout 30 npm run db:migrate:deploy || echo "⚠️ Migration completed or timed out (this may be normal)"
            
            echo "🔄 Restarting PM2..."
            pm2 stop tolstoy-api 2>/dev/null || true
            pm2 delete tolstoy-api 2>/dev/null || true
            
            # Start with environment variables from GitHub secrets
            echo "🔧 Starting application with environment variables..."
            pm2 start dist/main.js --name tolstoy-api \
              --env NODE_ENV=production \
              --env PORT=3000 \
              --env DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              --env DIRECT_URL="${{ secrets.DIRECT_URL }}" \
              --env AWS_REGION=us-east-1 \
              --env AWS_SECRET_NAME=tolstoy/env \
              --env USE_AWS_SECRETS=true \
              --env INNGEST_EVENT_KEY="${{ secrets.INNGEST_EVENT_KEY }}" \
              --env DAYTONA_API_KEY="${{ secrets.DAYTONA_API_KEY }}" \
              --env DAYTONA_BASE_URL="${{ secrets.DAYTONA_BASE_URL }}" \
              --env UPSTASH_REDIS_REST_URL="${{ secrets.UPSTASH_REDIS_REST_URL }}" \
              --env UPSTASH_REDIS_REST_TOKEN="${{ secrets.UPSTASH_REDIS_REST_TOKEN }}" \
              --env SENTRY_DSN="${{ secrets.SENTRY_DSN }}" \
              --log /home/ubuntu/logs/tolstoy.log \
              --error /home/ubuntu/logs/tolstoy-error.log \
              --output /home/ubuntu/logs/tolstoy-out.log \
              --time
            
            # Wait a moment for PM2 to start
            sleep 5
            
            # Check if PM2 started successfully
            if ! pm2 describe tolstoy-api > /dev/null; then
              echo "❌ PM2 failed to start the application"
              pm2 logs tolstoy-api --lines 10
              exit 1
            fi
            
            pm2 save
            
            echo "✅ Deployment completed successfully!"
          EOF

      - name: Health check
        run: |
          echo "⏳ Waiting for application to start..."
          sleep 20
          
          echo "🏥 Health check..."
          for i in {1..6}; do
            echo "Attempt $i/6..."
            if curl -f --connect-timeout 10 --max-time 30 http://${{ secrets.EC2_HOST }}/health; then
              echo "✅ Health check passed!"
              exit 0
            fi
            
            if [ $i -lt 6 ]; then
              echo "⏳ Waiting 10 seconds before retry..."
              sleep 10
            fi
          done
          
          echo "❌ Health check failed after 6 attempts"
          echo "🔍 Checking server status and logs..."
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" << 'DEBUG_EOF'
            echo "=== PM2 Status ==="
            pm2 status
            
            echo -e "\n=== Application Logs (last 30 lines) ==="
            pm2 logs tolstoy-api --lines 30
            
            echo -e "\n=== Port Check ==="
            ss -tlnp | grep :3000 || echo "Port 3000 not listening"
            
            echo -e "\n=== AWS Secrets Test ==="
            aws secretsmanager get-secret-value --secret-id tolstoy/env --region us-east-1 --query 'SecretString' --output text | head -c 50 && echo "..." || echo "AWS secrets not accessible"
            
            echo -e "\n=== System Resources ==="
            df -h | head -5
            free -h
          DEBUG_EOF
          exit 1

      - name: Cleanup
        if: always()
        run: rm -f ssh_key.pem